import matplotlib.pyplot as plt
import numpy as np
x = np.random.normal(0, 1, 100)
y = 2 * x + np.random.normal(0, 1, 100)
z = np.random.normal(1, 1.5, 100)
w = np.random.normal(-1, 0.5, 100)
fig, ax = plt.subplots()
ax.scatter(x, y, color='blue', marker='o', label='Set 1')
ax.scatter(z, w, color='green', marker='s', label='Set 2')
ax.scatter(np.random.normal(-2, 1, 100), np.random.normal(3, 1, 100), color='red', marker='^', label='Set 3')
ax.set_title('Scatter Plot Example')
ax.set_xlabel('X-axis')
ax.set_ylabel('Y-axis')
z1 = np.polyfit(x, y, 1)
z2 = np.polyfit(z, w, 1)
p1 = np.poly1d(z1)
p2 = np.poly1d(z2)
ax.plot(x, p1(x), color='red', linestyle='--', linewidth=2, label='Trend Line')
ax.plot(z, p2(z), color='black', linestyle='--', linewidth=2, label='Trend Line')
ax.legend(loc='upper left')
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.spines['bottom'].set_linewidth(1.5)
ax.spines['left'].set_linewidth(1.5)
ax.set_xlim([-4, 4])
ax.set_ylim([-4, 4])
ax.set_xticks([-4, -3, -2, -1, 0, 1, 2, 3, 4])
ax.set_yticks([-4, -3, -2, -1, 0, 1, 2, 3, 4])
plt.show()